language: python

dist: focal

jobs:
  include:
    # others still work and don't install python3.7
    - python: 'pypy3'

    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11

install:
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - "pip install wheel pip setuptools --upgrade"
  - "pip install -r requirements.txt --upgrade"
  - "pip install pytest"

script:
  - python setup.py build_ext --inplace
  - pytest -v -s

before_deploy: "echo 'ready'"

deploy:
  provider: pypi
  username: nooperpudd
  password:
    secure: vdY6WCJCvOS8W0mNC2z/bBDg2OVBss1IFg8BSH25NuziCTBEKbUi3BAwOdq45Ei24r5+2yVjKpAyhXSis8AvdVHBrM84IzpJQHdSLyTVJMexdT/830528IlyIhGVBGROCSIznFXIbfVvcyuTDBhAgBUj4xanjHnLJLMJsqpY8LI52hjGvANWRupp+czpsQTzYL5IVA7WMRoUBvKn7FzBs8ZwtssyeSsv0Ju40r5A942sXW/yjg3mDGF9RWgYaQJMl4VYpYKR7Ck4I0e51axjksZVxggIp1FXpX0jU5e1wt8n9pSl4mN7HSK72ooNlp9uHSAvOuSMvXlbXpHeM+u4HEEYAHJcX/T8DI5E2iAUjjZT3N5mRFR4IuyuvmY1UZ0wm9TvLDHzko3sX9I4JqA2MAILOHxu5rvUqDJ51pb5JCHiYlWpinMLlHVKA8zx6EJcu65TIKEmqqP2gXfJhyWLFLgNVRw3btpmNV51BJFFT7sDDtgKgoP1/glV+BResd0ZGvBQl0hCQtZiUOHQ/naM2+qVa4baysjSoQazwvKvc0D6akedpapQyR8eWPPzUhR0JtQ/qp1qps2DpFEoqAvU6YnYtYQOM1JiZAjRA5Lxyh/Bhh3hQZwWg/EbUnGs1MrUclWlLS9f7zwYzdGnCihPYlEF5cWMoJ+bQsYoYx7UdRo=
  distributions: "sdist"
  on:
    tags: true
    python: '3.10'
